import { Inter } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import { cn } from "@/lib/utils";
import NavBar from "@/components/navigation/NavBar";
import Footer from "@/components/Footer";
import PhoneNavBar from "@/components/navigation/PhoneNavBar";
import PhoneMenu from "@/components/navigation/PhoneMenu";
import ActiveMenuContextProvider from "@/context/activeMenuContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Deficonsa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn("m-0 p-0 relative", inter.className)}>
        <ActiveMenuContextProvider>
          <PhoneMenu />
          <PhoneNavBar />
          <NavBar />
          {children}
          <Footer />
        </ActiveMenuContextProvider>
      </body>
    </html>
  );
}


